"""Unit tests — GitAutoCommitter (P6)."""

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from backend.utils.domains.git.git_auto_committer import (
    FileCommitRecord,
    GitAutoCommitter,
    GitManifest,
)


def _make_committer(tmp_path: Path) -> GitAutoCommitter:
    logger = MagicMock()
    return GitAutoCommitter(
        project_root=tmp_path,
        logger=logger,
        llm_client=None,
        git_user_name="Test User",
        git_user_email="test@example.com",
    )


@pytest.mark.unit
class TestFileCommitRecord:
    def test_to_dict(self):
        rec = FileCommitRecord(
            rel_path="src/models.py",
            commit_sha="abc1234",
            commit_message="feat(models): auto-generated by developer agent",
            agent_type="DEVELOPER",
            lines_added=42,
            lines_deleted=0,
            unified_diff="@@ -0,0 +1,42 @@\n+...",
        )
        d = rec.to_dict()
        assert d["rel_path"] == "src/models.py"
        assert d["commit_sha"] == "abc1234"
        assert d["lines_added"] == 42


@pytest.mark.unit
class TestGitManifest:
    def test_to_dict_empty(self):
        m = GitManifest(project_name="myapp", repo_initialised=False, commits=[])
        d = m.to_dict()
        assert d["project_name"] == "myapp"
        assert d["commits"] == []

    def test_to_dict_with_commits(self):
        rec = FileCommitRecord("a.py", "sha1", "msg", "DEVELOPER", 1, 0, "")
        m = GitManifest("myapp", True, [rec])
        d = m.to_dict()
        assert len(d["commits"]) == 1
        assert d["commits"][0]["rel_path"] == "a.py"


@pytest.mark.unit
class TestGitAutoCommitterInit:
    def test_constructor(self, tmp_path: Path):
        c = _make_committer(tmp_path)
        assert c._project_root == tmp_path
        assert c._git_user_name == "Test User"

    @patch("subprocess.run")
    def test_init_repo_calls_git_init(self, mock_run, tmp_path: Path):
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        c = _make_committer(tmp_path)
        c._init_repo()
        calls_str = " ".join(str(a) for call_obj in mock_run.call_args_list for a in call_obj[0])
        assert "git" in calls_str
        assert "init" in calls_str

    @patch("subprocess.run")
    def test_commit_all_returns_manifest(self, mock_run, tmp_path: Path):
        mock_run.return_value = MagicMock(returncode=0, stdout="abc1234", stderr="")
        c = _make_committer(tmp_path)

        # Create fake file
        (tmp_path / "main.py").write_text("print('hello')")

        ordered = [{"rel_path": "main.py", "agent_type": "DEVELOPER", "content": "print('hello')"}]
        manifest = c.commit_all(ordered, "testproject")
        assert isinstance(manifest, GitManifest)
        assert manifest.project_name == "testproject"
