"""
GitAutoCommitter — Automatic Per-File Git Commits for Agent-Generated Projects.

After ``DomainAgentOrchestrator._finalize()`` writes all files to disk,
``_git_finalize()`` calls this module to:

1. ``git init`` the project directory (if not already a repo).
2. Configure local user identity (no global git config required).
3. Stage and commit each file individually in topological DAG order.
4. Capture the unified diff for each commit via ``git show --unified=5``.
5. Write ``git_manifest.json`` to the project root.

The ``git_manifest.json`` is then served by the Flask API so the War Room's
Diff Viewer can display per-file diffs when the user clicks a Kanban card.

Graceful degradation:
    - If ``git`` binary is missing: logs a warning, returns empty manifest.
    - If LLM is unavailable: falls back to template-based commit messages.
    - If a single file commit fails: logs error, continues with remaining files.

Usage::

    committer = GitAutoCommitter(project_root=Path("..."), logger=logger)
    manifest = committer.commit_all(ordered_files, project_name="myapi")
    manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2))
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from backend.utils.core.io.git_manager import GitManager
from backend.utils.core.system.agent_logger import AgentLogger


@dataclass
class FileCommitRecord:
    """Per-file entry written into ``git_manifest.json``."""

    rel_path: str
    commit_sha: str
    commit_message: str
    agent_type: str
    lines_added: int
    lines_deleted: int
    unified_diff: str


@dataclass
class GitManifest:
    """Root object written to ``<project_root>/git_manifest.json``."""

    project_name: str
    repo_initialised: bool
    commits: List[FileCommitRecord] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "project_name": self.project_name,
            "repo_initialised": self.repo_initialised,
            "commits": [asdict(c) for c in self.commits],
        }


class GitAutoCommitter:
    """
    Stages and commits generated project files one-by-one in topological order.

    Args:
        project_root:   Path to the generated project directory (files on disk).
        logger:         AgentLogger from the DI container.
        llm_client:     Optional synchronous LLM client. If provided, its
                        ``chat(messages, options_override)`` method is called
                        to generate a descriptive commit message. Falls back
                        to a deterministic template on any failure.
        git_user_name:  Local git config user.name (default "Ollash Agent").
        git_user_email: Local git config user.email.
    """

    _TEMPLATE_MESSAGE = "feat({stem}): auto-generated by {agent_type} agent"
    _LLM_SYSTEM_PROMPT = (
        "You are a concise git commit message writer. "
        "Given a file path and its content, write ONE conventional commit "
        "message (50 chars max, imperative mood, no period). "
        "Reply with only the commit message text — no explanation."
    )

    def __init__(
        self,
        project_root: Path,
        logger: AgentLogger,
        llm_client: Optional[Any] = None,
        git_user_name: str = "Ollash Agent",
        git_user_email: str = "agent@ollash.local",
    ) -> None:
        self._project_root = project_root
        self._logger = logger
        self._llm_client = llm_client
        self._git_user_name = git_user_name
        self._git_user_email = git_user_email
        self._git = GitManager(repo_path=str(project_root))

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def commit_all(
        self,
        ordered_files: List[Dict[str, Any]],
        project_name: str,
    ) -> GitManifest:
        """Init the repo and commit each file; return a populated GitManifest.

        Args:
            ordered_files: List of ``{"rel_path": str, "agent_type": str,
                           "content": str}`` dicts, ordered topologically.
            project_name:  Short project identifier (stored in manifest).

        Returns:
            GitManifest — may have ``repo_initialised=False`` if git is absent.
        """
        manifest = GitManifest(project_name=project_name, repo_initialised=False)

        if not self._ensure_git_available():
            self._logger.warning("[GitAutoCommitter] git not found — skipping auto-commit")
            return manifest

        if not self._init_repo():
            return manifest

        manifest.repo_initialised = True
        self._configure_repo_identity()

        for file_info in ordered_files:
            rel_path = file_info.get("rel_path", "")
            agent_type = file_info.get("agent_type", "DEVELOPER")
            content = file_info.get("content", "")
            if not rel_path:
                continue
            try:
                record = self._commit_single_file(rel_path, agent_type, content)
                if record is not None:
                    manifest.commits.append(record)
            except Exception as exc:
                self._logger.error(
                    f"[GitAutoCommitter] Failed to commit '{rel_path}': {exc}"
                )

        self._logger.info(
            f"[GitAutoCommitter] {len(manifest.commits)} commits for '{project_name}'"
        )
        return manifest

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _ensure_git_available(self) -> bool:
        result = self._git._run_git("--version")
        return result.get("success", False)

    def _init_repo(self) -> bool:
        git_dir = self._project_root / ".git"
        if not git_dir.exists():
            result = self._git._run_git("init")
            if not result.get("success"):
                self._logger.error(
                    f"[GitAutoCommitter] git init failed: {result.get('error', '')}"
                )
                return False
            self._logger.info(
                f"[GitAutoCommitter] git init at {self._project_root}"
            )
        return True

    def _configure_repo_identity(self) -> None:
        self._git._run_git("config", "--local", "user.name", self._git_user_name)
        self._git._run_git("config", "--local", "user.email", self._git_user_email)

    def _commit_single_file(
        self,
        rel_path: str,
        agent_type: str,
        content: str,
    ) -> Optional[FileCommitRecord]:
        # Stage the file
        add_result = self._git._run_git("add", rel_path)
        if not add_result.get("success"):
            self._logger.warning(
                f"[GitAutoCommitter] git add failed for '{rel_path}': "
                f"{add_result.get('error', '')}"
            )
            return None

        # Skip if nothing staged
        staged_check = self._git._run_git("diff", "--cached", "--stat", rel_path)
        if not staged_check.get("output", "").strip():
            return None

        message = self._build_commit_message(rel_path, agent_type, content)
        commit_result = self._git._run_git("commit", "-m", message)
        if not commit_result.get("success"):
            err = commit_result.get("output", "") + commit_result.get("error", "")
            if "nothing to commit" in err:
                return None
            self._logger.error(
                f"[GitAutoCommitter] commit failed for '{rel_path}': {err}"
            )
            return None

        sha_result = self._git._run_git("rev-parse", "--short", "HEAD")
        sha = sha_result.get("output", "").strip() if sha_result.get("success") else "UNCOMMITTED"

        numstat = self._git.show_numstat_for_commit(sha, rel_path)
        unified_diff = self._git.show_unified(sha, rel_path, context_lines=5)

        return FileCommitRecord(
            rel_path=rel_path,
            commit_sha=sha,
            commit_message=message,
            agent_type=agent_type,
            lines_added=numstat.get("added", 0),
            lines_deleted=numstat.get("deleted", 0),
            unified_diff=unified_diff,
        )

    def _build_commit_message(
        self,
        rel_path: str,
        agent_type: str,
        content: str,
    ) -> str:
        if self._llm_client is not None:
            try:
                messages = [
                    {"role": "system", "content": self._LLM_SYSTEM_PROMPT},
                    {
                        "role": "user",
                        "content": (
                            f"File: {rel_path}\n"
                            f"Agent: {agent_type}\n"
                            f"Content (first 400 chars):\n{content[:400]}"
                        ),
                    },
                ]
                response, _ = self._llm_client.chat(
                    messages,
                    options_override={"temperature": 0.2, "num_ctx": 1024},
                )
                generated = re.sub(r'["\']', "", response.get("content", "")).strip()[:72]
                if generated:
                    return generated
            except Exception as exc:
                self._logger.debug(f"[GitAutoCommitter] LLM message gen failed: {exc}")

        stem = Path(rel_path).stem
        return self._TEMPLATE_MESSAGE.format(
            stem=stem, agent_type=agent_type.lower()
        )

    @staticmethod
    def _parse_numstat_line(numstat_output: str) -> tuple:
        for line in numstat_output.splitlines():
            parts = line.split("\t")
            if len(parts) >= 2:
                try:
                    return int(parts[0]), int(parts[1])
                except ValueError:
                    pass
        return 0, 0
