from typing import Dict, List

ORCHESTRATION_TOOL_DEFINITIONS: List[Dict] = [
    {
        "type": "function",
        "function": {
            "name": "evaluate_plan_risk",
            "description": "Evaluates a plan_actions before executing it, detecting technical, security, and impact risks.",
            "parameters": {
                "type": "object",
                "properties": {
                    "plan": {
                        "type": "object",
                        "description": "The plan to evaluate, as generated by plan_actions.",
                    }
                },
                "required": ["plan"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "detect_user_intent",
            "description": "Classifies the user's real intent: exploration, debugging, change, audit, incident, learning.",
            "parameters": {
                "type": "object",
                "properties": {
                    "user_request": {
                        "type": "string",
                        "description": "The user's request text.",
                    }
                },
                "required": ["user_request"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "require_human_gate",
            "description": "Marks an action or set of actions as blocked until explicit human approval.",
            "parameters": {
                "type": "object",
                "properties": {
                    "action_description": {
                        "type": "string",
                        "description": "A clear description of the action to be gated.",
                    },
                    "reason": {
                        "type": "string",
                        "description": "Why human approval is required.",
                    },
                },
                "required": ["action_description", "reason"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "summarize_session_state",
            "description": "Summarizes the current state of the system, changes made, decisions taken, and pending risks.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "explain_decision",
            "description": "Explains why the agent made a specific decision and what alternatives it discarded.",
            "parameters": {
                "type": "object",
                "properties": {
                    "decision_id": {
                        "type": "string",
                        "description": "Optional ID of a past decision to explain.",
                    }
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "validate_environment_expectations",
            "description": "Checks if the current environment matches what is expected (OS, version, permissions, network).",
            "parameters": {
                "type": "object",
                "properties": {
                    "expectations": {
                        "type": "object",
                        "description": "A dictionary of expected environment attributes.",
                    }
                },
                "required": ["expectations"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "detect_configuration_drift",
            "description": "Detects deviations with respect to a known baseline.",
            "parameters": {
                "type": "object",
                "properties": {
                    "baseline_file": {
                        "type": "string",
                        "description": "Path to the baseline configuration file.",
                    },
                    "current_file": {
                        "type": "string",
                        "description": "Path to the current configuration file to compare.",
                    },
                },
                "required": ["baseline_file", "current_file"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "evaluate_compliance",
            "description": "Evaluates system configurations and practices against a specified compliance standard (e.g., ISO 27001, GDPR).",
            "parameters": {
                "type": "object",
                "properties": {
                    "compliance_standard": {
                        "type": "string",
                        "description": "The name of the compliance standard (e.g., 'ISO 27001', 'GDPR').",
                    },
                    "audit_scope": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "A list of areas or components to audit.",
                    },
                },
                "required": ["compliance_standard", "audit_scope"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_audit_report",
            "description": "Generates a structured report from previous tool outputs (e.g., security scan, compliance evaluation).",
            "parameters": {
                "type": "object",
                "properties": {
                    "report_format": {
                        "type": "string",
                        "enum": ["json", "text"],
                        "description": "The desired format of the report (e.g., 'json', 'text').",
                    }
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "propose_governance_policy",
            "description": "Proposes new governance policies or updates existing ones based on compliance gaps or best practices.",
            "parameters": {
                "type": "object",
                "properties": {
                    "policy_type": {
                        "type": "string",
                        "description": "The type of policy to propose (e.g., 'data_handling', 'access_control').",
                    },
                    "scope": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "The scope to which the policy applies.",
                    },
                },
                "required": ["policy_type", "scope"],
            },
        },
    },
]
